# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e516601b643b82df956d546822958436e39177214e8f625fff88e44a1c8db0cdf73ddad6f664dc34ff284678c8b7f1ce61bf7ce7ff5b806c24d6f6ace944bde

test:
  secret_key_base: a6a1ca344c315e2340a0607e9a61147c4e7768a759712568e2a0e4e235393c0a3b43cc52a0507a988c3ad035830b4ab8d251cc3e436e066613bbee5160e5c48f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
